### PR TITLE
V2.0  Julia 1.1.1, more accurate, Julia analyzer,MKL.jl, improvements 

### PR DESCRIPTION
**Pull request by aminya**
### Julia Main (JuliaMain-JuliaBench-JuliaBenchSIMD):

* Combined separated function files JuliaMatrixBenchmark and JuliaMatrixBenchmarkOp into JuliaBench and JuliaBenchSIMD respectively for easier access
* Used ``@benchmark`` instead of deprecated and inaccurate tic() and toq(), so all functions now just include the algorithm or operation. Benchmark result may not be comparable to ones in previous versions.
* ``@benchmarks`` calls allFunctions in local scope (using $). Then the minimum run time among different benchmarks for each function is chosen.
* Removed totalRunTime because it does not mean anything anymore
* Changed name of some variables and functions to more appropriate ones
* Used transpose() instead of deprecated .'
* Used DelimitedFiles.readdlm and DelimitedFiles.writedlm instead of deprecated readcsv and writescv
* Removed rounds because readdlim supports converting to int64 itself
* Changed deprecated squeeze to droplims
* jj for loop changed to be like fun in allFunctions. This allows simply adjusting allFunctions array if want to remove some functions from benchmark
* Added dims= to 2nd input argument of minimum(), maximum(), findmin() and sum() functions
* Added dummy mY to functions that don't use it. (for consistency in code logic)
* Changed deprecated expm with exp
* Changed deprecated sqrtm with sqrt
* eig changed with eigen.
* vClusterId modified to be compatible with Cartesian indexing
* mRunTime is stored in a mat file using MAT package.
* tRunTime is a table which has the run time information in a intuitive manner
* added 0 benchmark operation mode which is for fast testing only
* changed file and folder management
* now average of different iteration of Run Times is calculated (for different kk)
* automatic work directory setter
* In JuliaBenchSIMD, functions that are identical to non SIMD versions are removed from allFunctions
* Two types of BLAS is used (MKL.jl and default Julia Blas)

### Julia Analyzer (AnalyszeRunTimeResults-AnalysisJuliaPlotter):

* Julia Analyzer added for creating plots

###  Matlab Main (MatlabMain-MatlabBench):

* Use cRunTime cell and then tRuntime table to store run time data intuitively
* changed file and folder management
* use timeIt instead of tic and toc
* now the average of median of different iteration of Run Times is calculated (for different kk)
* some other changes to be the same as respective Julia function

### Matlab Analyzer (AnalyszeRunTimeResults-AnalysisInitScript):

* plotting algorithm improved
* use mat files instead of csv
* use of tables

### CODE REVIEW

**Comment by aminya** [comment]
Hi Royi, Were you able to take a look at my repository?

**Comment by RoyiAvital** [comment]
Hi...

I still haven't got a chance to have a look on this.
It won't be soon as I'm waiting for JulaiPro in MKL flavor to happen.

**Comment by aminya** [comment]
> 
> 
> Hi...
> 
> I still haven't got a chance to have a look on this.
> It won't be soon as I'm waiting for JulaiPro in MKL flavor to happen.

I will add the benchmark for Julia with openBlas as well.
Installing MKL.jl is very easy: https://github.com/aminya/MKL.jl/tree/patch-1#to-install

**Comment by RoyiAvital** [comment]
I'm not sure `MKL.jl` is a good solution to the problem as I'm not sure what are the compilation flags (Are they using the features to fully utilize Intel MKL?).

Also, I'm an average Windows user. I don't want to compile programs. I want to use distributed binaries.

**Comment by aminya** [comment]
> 
> 
> I'm not sure `MKL.jl` is a good solution to the problem as I'm not sure what are the compilation flags (Are they using the features to fully utilize Intel MKL?).
> 
> Also, I'm an average Windows user. I don't want to compile programs. I want to use distributed binaries.

This MKL.jl package is from JuliaComputing, which is the same company behind JuliaPro.
When you add MKL.jl it does everything automatically, from downloading Intel MKL, to configuring, etc. This is possible to do this because Julia supports Intel MKL natively! This package only adds it automatically. If you are not sure just try it on a different Julia install (like one JuliaPro and one native Julia) to have both openBlas and MKL.

**Comment by RoyiAvital** [comment]
I know where `MKL.jl` is originated.

It is not accurate to say Julia support MKL natively.
Julia uses standard BLAS calls hence it may use any BLAS library (Though I think BLAS Level 1 is implemented in Julia itself).

The MKL in used in `MKL.jl`, at least the last time I checked, is the one used by Anaconda distribution of Python. I don't know if it uses the advanced features of MKL (See my post at `MKL.jl` issues).

Also, As I wrote, I don't like the process of downloading and compiling (Or pseudo compiling as in this case) and then use. I want "Works out of the box" experience which means waiting for JulaiPro in MKL flavor.

For example, see the issue you have with the `PATH` (Actually your solution of adding this weird named folder to the path isn't  a good one in my opinion).

**Comment by aminya** [comment]
> 
> 
> I know where `MKL.jl` is originated.
> 
> It is not accurate to say Julia support MKL natively.
> Julia uses standard BLAS calls hence it may use any BLAS library (Though I think BLAS Level 1 is implemented in Julia itself).
> 
> The MKL in used in `MKL.jl`, at least the last time I checked, is the one used by Anaconda distribution of Python. I don't know if it uses the advanced features of MKL (See my post at `MKL.jl` issues).
> 
> Also, As I wrote, I don't like the process of downloading and compiling (Or pseudo compiling as in this case) and then use. I want "Works out of the box" experience which means waiting for JulaiPro in MKL flavor.
> 
> For example, see the issue you have with the `PATH` (Actually your solution of adding this weird named folder to the path isn't a good one in my opinion).

I totally understand your viewpoint, and I agree with most of it. However, the point of a benchmark is to compare what is already available, right?
P.S: Regarding my workaround for adding to the path, they're working on it if you see my pull request,

**Comment by RoyiAvital** [comment]
I'd be happy to see you post results on the linked thread comparing Julia with MKL vs. Julia with OpenBLAS.

Though, again, Julia doesn't take full advantage of MKL.
Still I expect MKL to win.

Back then my experience was MATLAB is faster for my computations since they are heavily dependent on the performance of the BLAS library.

**Pull request closed without merging**
