### PR TITLE
Disable multithreading in MATLAB

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by RoyiAvital** [comment]
I don't think we should "Limit" MATLAB to match Julia.

**Comment by ChrisRackauckas** [comment]
Well then you're not really comparing the same thing. You're comparing completely different algorithms. Of course an algorithm on 4-8 cores will be faster (by around 4-8x if both are optimal) than one which uses 1 core. This benchmark just reduces to saying "MATLAB uses implicit parallelism, but Julia doesn't yet", and can't say anything more. If you also show what happens when parallelism is turned off, a wealth of information is uncovered. I'd at least add another line in the graphs for MATLAB, and use it to show why implicit parallelism is so important.

**Comment by RoyiAvital** [comment]
I'm comparing what's the name of the test states, Array Operations With Linear Algebra in mind) using Julia and MATLAB for the Scientific Programmer.

Hence one have a platform, the computer, and an algorithm written in basic Linear Algebra operations.
This is the test, and those are the result.

It makes sense to optimize Julia code, but not limit MATLAB.

Developers of Julia language can do any other analysis to understand where their language stands and where to invest resources, but for the users, this is where things are.

**Comment by ChrisRackauckas** [comment]
>It makes sense to optimize Julia code, but not limit MATLAB.

No, it's not limiting MATLAB... it's finding out what the difference is...

>Developers of Julia language can do any other analysis to understand where their language stands and where to invest resources, but for the users, this is where things are.

That's exactly why you should put the other line...

**Comment by ChrisRackauckas** [comment]
If you want to actually have the benchmarks be helpful, you use them to attribute the differences to something. Otherwise these benchmarks are meaningless and say nothing. I am just asking for them to be meaningful: if they have a line which shows the difference when multithreading is on and off for MATLAB, it will show exactly that the difference is due to implicit parallelism (in the benchmarks I checked), and thus gives a concrete direction for Julia development.

**Comment by RoyiAvital** [comment]
First, you must remember that for simple array operation you get Memory Bounded pretty easily.
Hence it is not all int the Multi Threading thing.

More to that is maybe MATLAB we optimized (JIT Engine) in use cases where Multi Threading is there and hence, if you see Julia winning it it won't say Julia is good, it might be just MATLAB is bad in this test.

My point of view is what I get as a user.
You, as a developer can do the trick you did and get your own conclusions.

To be honest, I think the conclusions are so easy any one saw them:
1. Julia must improve its BLAS / LAPACK engine. Either by working with OpenBLAS thing or find a solution to Intel MKL (How come Anaconda ships with MKL?).
2. Julia must optimize its strength of the use of the `.` (Dot) operator. It is amazing feature.
3. Optimized broadcasting.
4. Julia needs Multi Threading (Efficient one, with options set by the user).

I think anyone saw that.

**Comment by ChrisRackauckas** [comment]
>To be honest, I think the conclusions are so easy any one saw them:

How can you say that without evidence?

**Comment by RoyiAvital** [comment]
Let's try explaining why I came to this conclusions:

1. We have tests which are pure BLAS / Lapack (The decompositions tests). MATLAB clearly wins there (Both libraries are multi threaded). Those tasks have large impact on other things in the daily work with Matrices (solutions to linear system, Eigen Values / Vectors problems, etc...).
2. MATLAB is fusing loops and uses both Multi Threading and SIMD on that. Yet they do that only for certain built in functions. Julia approach with the `.` means it will support any function is the way to go. It just not ready yet hence I expect 0.6 to close that. The conclusion is supported by the numbers of the Devectorized code.
3. The Broadcast Operation in Julia isn't Multi Threaded (Is is optimized to use SIMD?). In MATLAB it is. So clearly on operation which are not Memory Limited it will show (Hence I support your request to let the user set the mode and not only implicit parallelism). 
4. Julia has only experiential Multi Threading. Yet since resources are invested it means there are use case it is needed. When doing complex operation on an array in element wise (For "Easy Operation" you're memory bounded hence parallelism isn't good, another case where Julia, by letting the configuration set by the user will be more efficient) Multi Threading can assist greatly. It can be see.

What I don't understand is simple, you stated those conclusions by yourself (At least about Broadcasting, Using the Dot and Multi Threading).
You made a test which satisfied told you Julia is OK when using only one thread hence it seems we agree here.
What's the problem?

**Comment by ChrisRackauckas** [comment]
>We have tests which are pure BLAS / Lapack (The decompositions tests). MATLAB clearly wins there (Both libraries are multi threaded). Those tasks have large impact on other things in the daily work with Matrices (solutions to linear system, Eigen Values / Vectors problems, etc...).

Yes, I agree you have actual numbers here which are not currently explained. That is interesting.

>MATLAB is fusing loops and uses both Multi Threading and SIMD on that. Yet they do that only for certain built in functions. Julia approach with the . means it will support any function is the way to go. It just not ready yet hence I expect 0.6 to close that. The conclusion is supported by the numbers of the Devectorized code.

You cannot make any claim about multi-threading until you actually have that in the benchmarks. That's why I am asking for it.

>The Broadcast Operation in Julia isn't Multi Threaded (Is is optimized to use SIMD?). In MATLAB it is. So clearly on operation which are not Memory Limited it will show (Hence I support your request to let the user set the mode and not only implicit parallelism).

Again, you haven't shown this. What are the actual numbers?

>Julia has only experiential Multi Threading. Yet since resources are invested it means there are use case it is needed. When doing complex operation on an array in element wise (For "Easy Operation" you're memory bounded hence parallelism isn't good, another case where Julia, by letting the configuration set by the user will be more efficient) Multi Threading can assist greatly. It can be see.

What are the numbers?

I'm trying to help you take this general unfounded talk to something that has a foundation. There needs a comparison test for any factor you think actually matters.

**Comment by RoyiAvital** [comment]
@ChrisRackauckas , I really don't understand your point.

> You cannot make any claim about multi-threading until you actually have that in the benchmarks. That's why I am asking for it.

Yes I can. I can see MATLAB is using Multi Threading on my CPU.
They had Multi Threaded and SIMD optimized Element Wise operations for years.
Lately they added Loop Fusion:

https://www.mathworks.com/products/matlab/matlab-execution-engine.html

Again,
You're a Julia developer, you made the tests by yourself.
I make my tests, my agenda is which is faster to me in my use cases.
Those are the numbers. MATLAB is, at the moment, considerably faster.
Julia will catch up and in my opinion it is obvious to most how to do it.

If you think the conclusions are wrong, it is OK.

**Comment by ChrisRackauckas** [comment]
Okay, let's make this easy. How much of a difference does multithreading make? Is is 1.1x?

**Comment by RoyiAvital** [comment]
It will depend on how much the operation is memory bounded.
If it is not Multi Threading will scale almost linearly.

Hence I want the control for Multi Threading in Julia to be on the user side.

**Comment by ChrisRackauckas** [comment]
>It will depend on how much the operation is memory bounded.
If it is not Multi Threading will scale almost linearly.

For which of the multithreading tests is that true?

**Comment by RoyiAvital** [comment]
You can see in the Element Wise test that MATLAB is 2 times faster than Optimized Julia.

Why is that?
Well 2 tests in there are memory bounded due to their simplicity (Even if you write them with C with SSE Intrinsics, I tried it once). MATLAB pays there price for its Multi Threading overhead.
The third one, one root of the Quadratic Polynomial Function, is more complex hence MATLAB enjoys the scaling of Multi Threading.

The balance is that all in all MATLAB is faster only x2.

Anyhow, again, I'm not a Julia Language Developer.
I'm a MATLAB user wanted to be persuaded by Julia's performance and it is not up there yet.
One can see the potential, but not yet in real world.

To understand exactly what is holding back Julia is something which its developers will know better than me and I'm certain they will.

If you, as a developer of the language, has interest to understand exactly what happens behind the scene, please, do that.

For me, as a User, those are the results.
Currently, faster and better do my stuff on MATLAB.

**Comment by ChrisRackauckas** [comment]
>Well 2 tests in there are memory bounded due to their simplicity (Even if you write them with C with SSE Intrinsics, I tried it once). MATLAB pays there price for its Multi Threading overhead.

Why do you think it's simple enough that it's due to multithreading? Why do you think it accounts for more than 10% of the difference?

>If you, as a developer of the language, has interest to understand exactly what happens behind the scene, please, do that.

I'm not a language developer. This is just simple language user kinds of questions. Moreso, this is just general "how do you make a compelling and informative argument".

>For me, as a User, those are the results.
Currently, faster and better do my stuff on MATLAB.

Yes, but you can also be helpful...

**Comment by RoyiAvital** [comment]
I think I tried being helpful.

You can post results of yourself with MATLAB R2016b with its number of threads limited to 1.

Again, I think all Julia's developers got their conclusions by now.

All is good.
It was a fun thing to do.

**Pull request closed without merging**
